#!/bin/bash

usage() { echo "Usage: $0 [-u] device-id ..." 1>&2; exit 1; }

UNPASS=0

while getopts ":ud:" o; do
  case "${o}" in
    u)
      UNPASS=1
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

for d in "$@"; do
  vendor=$(cat /sys/bus/pci/devices/${d}/vendor 2>/dev/null)
  device=$(cat /sys/bus/pci/devices/${d}/device 2>/dev/null)

  if [ -z "${vendor}" ]; then
    echo "Device not found: ${d}" 1>&2
    exit 1
  fi

  if [ -e "/sys/bus/pci/devices/${d}/driver" ]; then
    echo "${d}" > "/sys/bus/pci/devices/${d}/driver/unbind"
#    while [ -e "/sys/bus/pci/devices/${d}/driver" ]; do
#      sleep 0.1
#    done
  fi
  if [ "${UNPASS}" -eq 0 ]; then
    echo "${vendor} ${device}" > "/sys/bus/pci/drivers/vfio-pci/new_id"
  fi
done

